### ISSUE TITLE
🔭 Force exclude a dependency from a plan

### ISSUE THREAD

**Issue by nonameplum** [swiftyfinch/Rugby#111]
## Is your feature request related to a problem? Please describe.
I would like to have the ability to _force exclude_ a specific dependency even though it is included in the plan by
```
- build
  - command: cache
    include: [Alamofire, SnapKit]
```

## Describe the solution you'd like
```
§ rugby --plan build --exclude Alamofire SnapKit
§ rugby --plan build -e Alamofire SnapKit
```

**Comment by swiftyfinch** [comment]
@nonameplum Hello!
Now you can add exclude to the plan. Like this:
```yml
- build
  - command: cache
    include: [Alamofire, SnapKit]
    exclude: [SomePod]
```

---

In this solution, there is a problem. Your plan can contain many different commands and also, some of them can be duplicated (like `drop` command). So, it's not easy to add a common interface for different user plans. And it's not clear how to manage additional flags if command duplicates.
```powershell
rugby --plan build --exclude Alamofire SnapKit
rugby --plan build -e Alamofire SnapKit
```

**Comment by swiftyfinch** [comment]
But anyway, thank you for your request, and feel free to add some more info or implement a draft.

**Comment by swiftyfinch** [comment]
Feel free to reopen the issue if you have more information

**Comment by swiftyfinch** [comment]
Yeah, I see. Thank you for your answer.

But we can't limit the plan with only one drop command. Someone already can use several drop commands in one plan. So we need a more general solution. The same with other different fields of each command of Rugby. There can be corner cases. But I think I understand your idea.

Right now It looks like a complex feature request for me.
So, let's reopen it, but sorry I don't have enough free time to implement any request for now.

Also, maybe you can find these features useful for your needs:
- You can read all code with such option: https://github.com/swiftyfinch/Rugby/blob/main/Docs/Cache.md#keep-pods-group-in-project
- Here you can create a base plan and reuse it in your other plans: https://github.com/swiftyfinch/Rugby/blob/main/Docs/Plans.md#-generate-example

**Comment by swiftyfinch** [comment]
Hello! I've decided to close the issue, because there is not enough demand.

Feel free to reopen it if it's still important to you.
And let's collect more votes for this feature request.
