### ISSUE TITLE
🔭 Add option --quiet for Cache command 

### ISSUE THREAD

**Issue by Lutzifer** [swiftyfinch/Rugby#112]
## Is your feature request related to a problem? Please describe.
When using rugby to speed up build on CI, the progress generates a very long log.

## Describe the solution you'd like
When I specify '--quiet', the progress log is not shown.

## Describe alternatives you've considered
I considered filtering the output on CI, but think that doing it with a flag is the better solution

**Comment by Lutzifer** [comment]
@swiftyfinch Thanks a lot!

**Comment by swiftyfinch** [comment]
@Lutzifer You're quite welcome!
