### ISSUE TITLE
🐛 The operation couldn’t be completed. (Rugby.Lockfile.LockFileError)

### ISSUE THREAD

**Issue by XiFengLang** [swiftyfinch/Rugby#113]
## Did you already try Rugby doctor?
Yes, and without any error message.

## Describe the bug

I executed `rugby cache --arch arm64 --sdk ios` after executing `pod install`, and an error occurred.

```C
> rugby cache --arch arm64 --sdk ios
Prepare Read project ✓
⛔️ Error: The operation couldn’t be completed. (Rugby.Lockfile.LockFileError error 0.)
🚑 Call doctor for more help: rugby doctor
```

I don't know why I'm getting this error all of a sudden, because I used to use rugby smoothly. I've tried `rugby clean` or manually deleting files other than `plan.yml`, and even reinstalling rugby, nothing worked to me.

## To Reproduce
1. `pod install`
2. `rugby cache --arch arm64 --sdk ios`
3. See an error

## Expected behavior

no error.

## Screenshots

![image](https://user-images.githubusercontent.com/14857242/149287633-b13a5228-fdff-4a5c-b6bf-4bf50943f631.png)

## Environment (please complete the following information):
 - Version [e.g. 1.15.0]
 - Logs (use `rugby doctor`)

```C
🚑 If you have any problems, please try these solutions.
After each one, you need to repeat your usual workflow.

1. Update 🏈 Rugby to the last version:
   mint install swiftyfinch/rugby
2. Add ignore option rugby --ignore-checksums.
   Be careful, you can't pass this option to plans command this way;
3. Try rugby clean before repeating your usual workflow;
4. Try to clean up your DerivedData and use rugby clean together;
5. Check that Pods project builds successfully without Rugby.

By the way, you can try to investigate build logs by yourself:
.rugby/rugby.log
.rugby/build.log
.rugby/rawBuild.log
and more there .rugby/history

Report an issue in GitHub discussions or any convenience support channel.
Attach last files from .rugby/history folder.
But be sure that there are no sensitive data.
```

 - Podfile or Example project (if you can share these)

sorry, i can not share the podfile，but i can run project success after pod intsall

**Comment by XiFengLang** [comment]
Empty the DerivedData directory worked for me。 `$HOME/Library/Developer/Xcode/DerivedData`

**Comment by swiftyfinch** [comment]
@XiFengLang Did you already manage that issue?
Rugby can't parse your `Podfile.lock`.

If you can't share it, could you debug it yourself?
1. Clone Rugby
2. In Rugby scheme you need to select `Options -> Working Directory` and input your project directory
3. Then just run the scheme and check the error

**Comment by XiFengLang** [comment]
Ok, if I can meet it, I will debug locally.

**Comment by bharathns** [comment]
I am seeing this issue i cleared the deriveddata but did not help

**Comment by swiftyfinch** [comment]
Could you share `EXTERNAL SOURCES` block from your `Podfile.lock`?
I think there is an unexpected fields which 🏈 Rugby just can't parse.

**Comment by XiFengLang** [comment]
> I am seeing this issue i cleared the deriveddata but did not help. after debugging I found its something to do with "EXTERNAL SOURCES"

Also need to execute `cmd + shift + K` to clean builds.

**Comment by XiFengLang** [comment]
I tried these steps and it worked out reassuringly, although I don't know what the problem is. 

1. remove `$HOME/Library/Developer/Xcode/DerivedData`
2. Run `rugby clean` or manually deleting files other than `plan.yml`
3. Run `cmd + shift + K` to clean builds.

**Comment by swiftyfinch** [comment]
@Xifengling @bharathns Thanks for description, but unfortunately I need more information.

Let's clear it up. I have a lot of projects which using Rugby and also we have CI job for each change.
And everything is fine. So, there is a special case of parsing `Podfile.lock` which I didn't see before.

I can't fix problem without reproducing it. Could you share your `Podfile.lock` or part of it with `EXTERNAL SOURCES`?
Or could you break `Rugby/TestProject` and then I will try to fix it as soon as possible.

**Comment by bharathns** [comment]
No issues sorry could not update @bharathns i am debugging it will let you know cannot share the podfile.lock thanks for the reply

**Comment by bharathns** [comment]
I know the reason too. Its this piece of code
object[.externalSources]  this returns values but
This ((object[.externalSources] ?? [:]) as? [String: [String: String]]) returns nil so the mapping is not happening
private static func parseExternalSources(_ object: [String: Any]) throws -> [String: [String: String]] {
        try ((object[.externalSources] ?? [:]) as? [String: [String: String]])
            .unwrap(orThrow: LockFileError.incorrectObject(.externalSources))
    }

**Comment by swiftyfinch** [comment]
@bharathns @XiFengLang Please, try this patch and let me know if it helps:
```shell
mint install swiftyfinch/rugby@bugfix/external-sources
```

**Comment by bharathns** [comment]
works!! @swiftyfinch  awesome thanks

**Comment by swiftyfinch** [comment]
Okay 🚀
Please, use `mint install swiftyfinch/rugby@main` before I can release new version 👍
