### ISSUE TITLE
Pod with unit test bundle resource build failed after `rugby cache`

### ISSUE THREAD

**Issue by blastmann** [swiftyfinch/Rugby#134]
## Describe the bug

Pod with unit test bundle resource build failed after `rugby cache`.

Look like the `FilePatcher` won't patch the subspec target.

## To Reproduce

1. Download the sample project: [podWithTestSpec.zip](https://github.com/swiftyfinch/Rugby/files/8031566/podWithTestSpec.zip)
2. Execute `pod install && rugby`
3. Build target `testPod-Unit-Tests` and it fails.

## Expected behavior

All the path list in `resource.sh` should have a correct patch.

## Screenshots

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/2032369/153174258-1647f068-9ad7-4004-a277-7c894e5fc36c.png">

## Environment (please complete the following information):
 - 1.17.0

**Comment by swiftyfinch** [comment]
Hello! Oh, I see. I think you are right, we need to use product names with target names in patcher regex.

**Comment by swiftyfinch** [comment]
I'll check it out week

**Comment by swiftyfinch** [comment]
@blastmann Could you check this branch `bugfix/patch-products`?

**Comment by blastmann** [comment]
This branch `bugfix/patch-products` works perfectly.

**Comment by swiftyfinch** [comment]
OK, I'll open pull request soon. But I need some time for regress.

**Comment by blastmann** [comment]
I have issue with some other cases, but I can't reproduce it with a new project. I will provide a new sample project when I reproduced.

**Comment by swiftyfinch** [comment]
@blastmann I've merged pull request 🚢
Feel free to reopen this issue if you have another case or just open the new one.
