### ISSUE TITLE
For some pods the `PODS_ROOT` value is null

### ISSUE THREAD

**Issue by fedejordan** [swiftyfinch/Rugby#136]
## Did you already try Rugby doctor?
Yes

## Describe the bug
I'm testing rugby integration in my project and seems that for some pods the `PODS_ROOT` environment value is null.
The failure is in the `xcodebuild` command.

If I replace the `${PODS_ROOT}` value with the absolute one (with my user and the project path) its working for these group of pods. The other pods that I have in my project don't have the issue. In total there are around ~35 pods.

## To Reproduce
Just a project with the following pods:
- Appsflyer
- Apptimize
- iProov

## Expected behavior
I would expect to use the `PODS_ROOT` in these pods as well

## Screenshots
Output of `rugby` command with the `PODS_ROOT`:
![image](https://user-images.githubusercontent.com/5657224/154820119-568a4044-c2ef-4632-959c-43cc7e891ec8.png)

Output of `rugby` command hardcoding the path:
![image](https://user-images.githubusercontent.com/5657224/154820356-d4ed4885-06c2-4dbb-b94d-e401743effe9.png)

This is how I had the `Build Phases -> [CP] Copy XCFrameworks` for Appsflyer target

![image](https://user-images.githubusercontent.com/5657224/154820138-21ea34a2-f9ef-47b6-acb8-89455bcc38b1.png)

Also noted that after running `rugby` successfully these pods are not being included in the `Pods-{project}` target 
![image](https://user-images.githubusercontent.com/5657224/154820385-e53d8477-932b-4936-ab93-5c8da4ac4f89.png)

## Environment (please complete the following information):
 - rugby 1.17.0
 - cocoapods 1.10.0
 - Xcode 13.2

Unfortunately I can't share logs for the project

Thanks in advance

**Comment by swiftyfinch** [comment]
@fedejordan Hello! Thank you so much for the detailed description 👍

I tried to reproduce this issue in TestProject here `demo/issue-136`.
But it works well for me. Could you try to break TestProject base on this branch?

Also, I will run regress on this branch. Let's see how it will be:
https://github.com/swiftyfinch/Rugby/actions/runs/1872330571

**Comment by swiftyfinch** [comment]
> If I replace the ${PODS_ROOT} value with the absolute one

In the last version of Rugby we don't use `${PODS_ROOT}`. Only an absolute path to `.rugby` folder.
So it looks strange to me and unfortunately, I don't have any ideas for now.

**Comment by swiftyfinch** [comment]
> Also, I will run regress on this branch. Let's see how it will be:
https://github.com/swiftyfinch/Rugby/actions/runs/1872330571

Pipeline failed, I'll check it 👀

**Comment by fedejordan** [comment]
Also I have noted that I have to replace all `import SomePod` with `import Pods_MyProject` does it make sense? If I don't do it I get errors like `No such module SomePod`

**Comment by fedejordan** [comment]
> > If I replace the ${PODS_ROOT} value with the absolute one
> 
> In the last version of Rugby we don't use `${PODS_ROOT}`. Only an absolute path to `.rugby` folder. So it looks strange to me and unfortunately, I don't have any ideas for now.

I know but seems that the value is null for these pods. Maybe there is another setting to these pods in my project

**Comment by fedejordan** [comment]
In my Podfile I have these versions:
```
pod 'Apptimize', '~> 3.4.7'
pod 'segment-appsflyer-ios', '~> 6.3.0'
pod 'Segment-Apptimize', '~> 0.3.2'
pod 'JumioMobileSDK/NetverifyBase', '3.9.1'
pod 'JumioMobileSDK/NetverifyFace+iProov', '3.9.1'
```

Sorry I forgot the part that these are being installed though Segment

**Comment by fedejordan** [comment]
I tried to compile the `demo/issue-136` branch and I got this error:

![image](https://user-images.githubusercontent.com/5657224/155020499-015f7c80-3dcb-4b61-b16b-4535e786cb91.png)

do I have to change my Xcode version?

**Comment by fedejordan** [comment]
I got an update. Just created an empty project with all the pods in my project Podfile. Run `bundle exec pod install && rugby`, opened Xcode and it built.

**Comment by swiftyfinch** [comment]
Do we still have an issue here? Or I just will check the failed GitHub pipeline.

**Comment by swiftyfinch** [comment]
As I see something is wrong with `pod 'Jumio Mobile SDK/NetverifyFace+iProov', '3.9.1'` in TestProject.
But it's not Rugby issue, because I got the same error without Rugby.

> Assertions: System: Failed to load the test bundle. If you believe this error represents a bug, please attach the result bundle at \~/Library/Developer/Xcode/DerivedData/TestProject-azqgujnxqxnqvocrwzolfdofwewi/Logs/Test/Test-TestProject-2022.02.22_22-45-34-+0500.xcresult. (Underlying Error: The bundle “TestProjectUITests” couldn’t be loaded. The bundle couldn’t be loaded. Try reinstalling the bundle. dlopen(\~/Library/Developer/CoreSimulator/Devices/3FB60792-B8D1-4F87-B677-145CD899A3A6/data/Containers/Bundle/Application/7353E177-8DB1-41CF-9151-B5C5849A2539/TestProjectUITests-Runner.app/PlugIns/TestProjectUITests.xctest/TestProjectUITests, 0x0109): Symbol not found: _$s8SocketIO0A11ClientEventO10disconnectyA2CmFWC
Referenced from: \~/Library/Developer/CoreSimulator/Devices/3FB60792-B8D1-4F87-B677-145CD899A3A6/data/Containers/Bundle/Application/7353E177-8DB1-41CF-9151-B5C5849A2539/TestProjectUITests-Runner.app/PlugIns/TestProjectUITests.xctest/Frameworks/iProov.framework/iProov
Expected in: \~/Library/Developer/CoreSimulator/Devices/3FB60792-B8D1-4F87-B677-145CD899A3A6/data/Containers/Bundle/Application/7353E177-8DB1-41CF-9151-B5C5849A2539/TestProjectUITests-Runner.app/PlugIns/TestProjectUITests.xctest/Frameworks/SocketIO.framework/SocketIO)

**Comment by swiftyfinch** [comment]
Now pipeline is green without `pod 'Jumio Mobile SDK/NetverifyFace+iProov', '3.9.1'`
https://github.com/swiftyfinch/Rugby/actions/runs/1883113344

It looks like this pod contains some issues because UI tests were broken.

**Comment by fedejordan** [comment]
> Do we still have an issue here? Or I just will check the failed GitHub pipeline.

I could make it work for a empty project, but don't know why in my real project I keep getting this error `No such module SomeModule`. 
Tried cleaning project, deleting derived data, closed and open Xcode, `rugby clean`

**Comment by swiftyfinch** [comment]
Do you have some specific settings in your Podfile? I think it can be an issue

**Comment by swiftyfinch** [comment]
@fedejordan Hello! Do you have any updates?

I've made some changes in the `main` branch. So, I wonder probably it will fix your issues.
You can update Rugby like this:
```shell
mint install swiftyfinch/rugby@main
```

**Comment by fedejordan** [comment]
Hi! I didn’t take the time to test it again. But will do and keep you updated. Thanks!

**Comment by swiftyfinch** [comment]
@fedejordan Feel free to reopen the issue if it is still reproduced

**Comment by fedejordan** [comment]
Another issue, when comparing my project with the TestProject (with all the pods that I have to use), some files are missing. Comparing `/Users/fjordan/Repositories/{TestProject/MyProject}/.rugby/build/{Debug/DevDebug}-iphonesimulator/TinyConstraints` build folder:

My project `Modules` folder

<img width="600" alt="headers2" src="https://user-images.githubusercontent.com/5657224/186477928-4bf10b35-2ec0-4ef0-8165-3eccd22fe86e.png">

TestProject `Modules` folder

<img width="600" alt="headers2" src="https://user-images.githubusercontent.com/5657224/186477957-8f75437f-0795-4668-8d6f-7fbdd022d13e.png">

My project `Headers` folder

<img width="600" alt="headers1" src="https://user-images.githubusercontent.com/5657224/186477991-d9a855f8-bd21-44b4-a409-e07fc349625d.png">

TestProject `Headers` folder

<img width="600" alt="headers2" src="https://user-images.githubusercontent.com/5657224/186478014-abb3803f-c898-440d-a185-59bbbfc28a65.png">

Hope these analysis could give us a clue about what is missing/happening! Thanks for your help!

**Comment by swiftyfinch** [comment]
@fedejordan Hello! Rugby has an option `-c, --config` and you can pass any value there.

```shell
-c, --config <config>   Build configuration. (default: Debug)
```

https://github.com/swiftyfinch/Rugby/blob/main/Docs/Cache.md#build-for-specific-configuration

In your case, it will be like this: `rugby cache -c DevDebug`.

Please, check it first of all. I hope it will solve all your problems 🤞

**Comment by fedejordan** [comment]
I've just realized that after reviewing the source code of Rugby 😅. 

After using `rugby --config DevDebug` it worked like a charm! Without the script to fix the `PODS_ROOT` issue (seems that it was related to some kind of file system problem then)

So all the problems were fixed!

I have a final question, when I reviewed the source code of the cache step I found this code:

```swift
// For build configuration name use Debug by default.
if config == nil { config = CONFIG.debug }
```

is there some possibility to obtain project/workspace current configs? I mean, maybe instead of assuming a "Debug" (which I understand that it's the common pattern in most projects), it could use the first configuration that is found there.
I found that if I use `xcodebuild -project MyProject.xcodeproj -list` it shows the current targets, build configurations (we can obtain the first one from here) and the schemes, we can obtain the default config from there. Hope it helps improving the tool!

**Comment by swiftyfinch** [comment]
> I have a final question, when I reviewed the source code of the cache step I found this line:
> 
> // For build configuration name use Debug by default.
> if config == nil { config = CONFIG.debug }
> is there some possibility to obtain project/workspace current configs? I mean, maybe instead of assuming a "Debug" (which I understand that it's the common pattern in most projects), it could use the first configuration that is found there.
> 
> I found that if I use xcodebuild -project MyProject.xcodeproj -list it shows the current targets, build configurations and the schemes, so maybe we can obtain the default config from there, using the first project configuration. Hope it helps improving the tool!

I think that it can be unexpected what config will be used while running `rugby` command. Yeah, it can be the first from the configs list, but this list can be changed by somebody. And we get different behavior of the same `rugby` command.

Also, unfortunately, it will break back compatibility with the current implementation.
