### ISSUE TITLE
multi(Watch, Widget) target extension failed: framework not found Alamofire

### ISSUE THREAD

**Issue by lakshminaidu** [swiftyfinch/Rugby#139]
## Did you already try Rugby doctor?
Use `rugby doctor` as a self-diagnostic tool.

## Describe the bug
Almofire compiler error on watch target.

## To Reproduce
1. add watch and widget targets and almofire pods for all targets
2. install rugby
3. Alomofire is not found for watch and widget
4. See an error

## Expected behavior
Should run the project which is not happening.
<img width="726" alt="Screen Shot 2022-03-14 at 10 37 23 AM" src="https://user-images.githubusercontent.com/12558090/158126288-2fd26efe-a608-4434-8659-86e8649df0b4.png">

## Environment (please complete the following information):
 - Version [e.g. 1.13.0]
 - Logs (use `rugby doctor`)
 - Podfile or Example project (if you can share these)

**Comment by swiftyfinch** [comment]
Hello, please check out this discussion https://github.com/swiftyfinch/Rugby/discussions/36#discussioncomment-1033537

**Comment by swiftyfinch** [comment]
Also, I've added this limitation to the main page:
https://github.com/swiftyfinch/Rugby/blob/main/README.md#known-limitations

So, it's not a bug. Nowadays it's by design.
You can open a feature request and feel free to contribute if you like.
