### ISSUE TITLE
🔭 Using relative paths

### ISSUE THREAD

**Issue by knbx** [swiftyfinch/Rugby#153]
First of all, I wanted to say thanks. This project looks really nice, early testing indicated it cuts our build time in half!

## Is your feature request related to a problem? Please describe.
Our repo has the pods folder checked in (which is somewhat [recommended by the cocoapods team](https://guides.cocoapods.org/using/using-cocoapods.html#should-i-ignore-the-pods-directory-in-source-control)). 
I noticed that running Rugby changed some relative filepaths in the Pods folder to absolute paths. This is of course detrimental when the Pods folder is shared across different computers with different locations.

## Describe the solution you'd like
I saw Rugby recently switched to absolute paths (#128) to fix another issue. In the PR, possble solutions using extra variables are mentioned. Ideally for our use case, we would use relative paths from the repo root. 

## Describe alternatives you've considered
Removing the Pods folder from git would fix this issue, but has other downsides
- podfile.lock isn't guaranteed to reproduce the exact same code (which has security implications)
- no longer able to build from git without running scripts (useful for CI / switching branches / onboarding)

## Additional context
Example of changed paths in Pods folder:
![image](https://user-images.githubusercontent.com/5506814/171129673-e345c1ad-dc39-44b6-a119-db5121a7544f.png)

**Comment by swiftyfinch** [comment]
Hello! Thank you for detailed request.
I think we can add flag like `rugby cache --relative-paths` and keep previous behaviour.

**Comment by swiftyfinch** [comment]
@knbx Hey! You can try it from the main branch before the new release.
```bash
mint install swiftyfinch/rugby@main
```

**Comment by knbx** [comment]
Hey @swiftyfinch, I've tested the main branch and it looks great!

Thanks for speeding up our builds ;D

**Comment by swiftyfinch** [comment]
You are welcome! 🚀
