### ISSUE TITLE
🐛 Rugby fails

### ISSUE THREAD

**Issue by mchirino89** [swiftyfinch/Rugby#187]
## Did you already try Rugby doctor?
Yes, I followed all of the suggested steps and the issue persists.

## Describe the bug
Rugby isn't able to run successfully in the sample project

<img width="1615" alt="CleanShot 2022-08-15 at 3 48 40@2x" src="https://user-images.githubusercontent.com/1657723/184697115-1e3f6613-aabd-48f7-a0a1-e64327ce97a8.png">

At first I thought it was a problem similar to the one described [here](https://stackoverflow.com/a/66908405/2376336) but even after following those steps too, still no luck.

## To Reproduce

1. Download [sample project](https://github.com/mchirino89/RugbyTest)
1. Install pods
2. Verify the project builds successfully3. 

![Untitled](https://user-images.githubusercontent.com/1657723/184697985-d77d33cb-b93b-45a9-967c-3b39b6da2454.jpg)

3. Execute `rugby`
4. See the error stated above

## Expected behavior
Rugby succeed (at least partially) the way it does with other projects

<img width="670" alt="CleanShot 2022-08-15 at 4 02 25@2x" src="https://user-images.githubusercontent.com/1657723/184699709-f7d10336-1183-4a1b-8f16-ccf2c86b7cb0.png">

## Screenshots
See them above

<img width="825" alt="CleanShot 2022-08-15 at 3 56 09@2x" src="https://user-images.githubusercontent.com/1657723/184698179-b0358bf2-2f9f-4b98-9b0b-ab2bb30663d3.png">

## Environment (please complete the following information):
 - Version 1.20.1
 - Cocoapods 1.11.3
 - [Example project](https://github.com/mchirino89/RugbyTest)

**Comment by swiftyfinch** [comment]
Hello @mchirino89!

I can't reproduce this issue. I downloaded your project and followed your steps, but everything is fine for me.
What version of Xcode do you use? Also, you can send your `.rugby/history` to this issue or to the email from my GitHub account.
The best way to reproduce the issue is using TestProject from this repository. You can fork Rugby, change this TestProject Podfile, and open a merge request. If you break CI pipeline I will see how to reproduce your issue. It can help me a lot.

Thank you for your investigation and verbose description of the issue.

**Comment by mchirino89** [comment]
Hey @swiftyfinch, thanks for the speedy response.

I'm using Xcode 13.4

I'll follow the steps you mentioned in order to see if I can replicate the bug on the CI.

I'll keep you posted.

> Thank you for your investigation and verbose description of the issue.

Please, It's the less I can do.

**Comment by mchirino89** [comment]
It seems the bug got scared when It sensed you, I now got a perfect execution with the same dependencies on the empty test project

<img width="825" alt="CleanShot 2022-08-16 at 5 28 38@2x" src="https://user-images.githubusercontent.com/1657723/184978974-4c0cabbc-d963-4e2d-8ef3-edead2c040f2.png">

I'm going to fork this repo and try to break the CI with my exact same `Podfile`

**Comment by swiftyfinch** [comment]
OK, let me know if the issue still exists 👍

**Comment by mchirino89** [comment]
> OK, let me know if the issue still exists 👍

Hey man! We're working on a workaround for this on our project. I think we can close this, thanks for the support!
