### ISSUE TITLE
Use HOME_DIR for cache

### ISSUE THREAD

**Issue by makleso6** [swiftyfinch/Rugby#193]
Is it possible to use HOME_DIR for cache instead current project folder?

**Comment by swiftyfinch** [comment]
Hello! No, it's impossible in the current version. I think it will break backward compatibility right now.

I'm working on the next major release and I'm pretty sure that it will be as default behaviour there.
But I'm not ready to share this one and can't predict release date right now. Keep tuned in)

**Comment by swiftyfinch** [comment]
@makleso6 Also, it can be related with #153 if you try to use 🏈 Rugby on CI.

**Comment by makleso6** [comment]
Thanks! At the moment I move `.rugby` folder from HOME_DIR to current project folder (Our CI supports only HOME_DIR  folders cache)
I close issue
