### ISSUE TITLE
Rugby does not rebuild when changing rosetta mode

### ISSUE THREAD

**Issue by michaellevel** [swiftyfinch/Rugby#204]
## Did you already try Rugby doctor?
Yes

## Describe the bug
When I use rugby in non-rosetta mode then enable rosetta I get "Symbol not found for architecture arm64".

## To Reproduce
1. Turn off Rosetta mode
2. `rugby cache -s ios` 
3. Turn on Rosetta mode
4. Compile

## Expected behavior
Rugby rebuild for the current architecture.

## Environment (please complete the following information):
 - Version 1.21.0

## Additional context
Could Rugby detect which version of Xcode I use and rebuild based on that?

**Comment by swiftyfinch** [comment]
Hello @michaellevel! First of all, thank you for your issue description.
Rugby uses `xcodebuild` under the hood and as I know it's not related to Xcode mode.

Are you sure that your problem in Rosetta mode? Have you already seen this documentation?
https://github.com/swiftyfinch/Rugby/blob/main/Docs/Cache.md

If you see an error `"Symbol not found for architecture arm64"`, I hope you just need to select this architecture `rugby --arch arm64`. Have you tried it?

Maybe I didn't understand you correctly, so I please could you add more information?

**Comment by michaellevel** [comment]
I use rosetta mode now and I'm going back and forth and when I do Rugby doesn't rebuild anything and I see errors. Let me reproduce this and I'll get better steps.

I use `rugby cache -s ios` and the docs say the default for `ios` is `arm64`. Did I interpret that correctly?

**Comment by swiftyfinch** [comment]
> I use rosetta mode now and I'm going back and forth and when I do Rugby doesn't rebuild anything and I see errors. Let me reproduce this and I'll get better steps.

OK, no problem. Take your time. Also, have you try to check this behaviour without using Rugby? Is it the same or not?

> I use rugby cache -s ios and the docs say the default for ios is arm64. Did I interpret that correctly?

Yes, that's right.

**Comment by michaellevel** [comment]
To fix the issue, I run `pod install`. But to use rugby again I needed to delete all the folder. Using clean didn't work, but to be certain I'll reproduce. Great tool btw!

**Comment by swiftyfinch** [comment]
Yeah, you should use `rugby rollback` or `pod install` between rugby calls.
Are we ready to close the issue?

🏈 Thank you! I'm working on the next major version. Stay tuned)

**Comment by swiftyfinch** [comment]
Feel free to add more information and reopen the issue
