### ISSUE TITLE
Crash when using useContentChecksums

### ISSUE THREAD

**Issue by mlch911** [swiftyfinch/Rugby#208]
Crash in [`CombinedChecksum.swift:106`](https://github.com/swiftyfinch/Rugby/blob/5532a6e0672605f7023690b2cf243425d9f2b09e/Sources/Rugby/Commands/Cache/Other/Checksums/CombinedChecksum.swift#L106)
The `URL.`
These Symlinks will crash this.

```
Error: [0mError Domain=NSCocoaErrorDomain Code=256 "The file “_Pods.xcodeproj” couldn’t be opened." UserInfo={NSFilePath=PathToLocalPod/_Pods.xcodeproj, NSUnderlyingError=0x60000502ce70 {Error Domain=NSPOSIXErrorDomain Code=21 "Is a directory"}}
```

**Comment by swiftyfinch** [comment]
@mlch911 Hello! It looks strange.
Why your pod folder contains `"_Pods.xcopeproj"` folder?

Usually, each pod should be independent of the others. Is it so necessary for you to have symlinks in a pod folder? Is it kind of crosslink between them?

Could you try the method https://developer.apple.com/documentation/foundation/url/1779822-resolvingsymlinksinpath for resolving symlinks and then test it in your case?

**Comment by mlch911** [comment]
> 

Yes. I added this in the PR https://github.com/mlch911/Rugby/blob/3a491813b52c54c22648ebd25aaa89d4f8cdc03a/Sources/Rugby/Commands/Cache/Other/Checksums/CombinedChecksum.swift#L107

**Comment by swiftyfinch** [comment]
#209
