### ISSUE TITLE
🐛 dyld[27159]: Library not loaded: @rpath/DeviceKit.framework/DeviceKit

### ISSUE THREAD

**Issue by anil291987** [swiftyfinch/Rugby#216]
## Did you already try Rugby doctor?
Use `rugby doctor` as a self-diagnostic tool.

## Describe the bug
After run `pod install && rugby`

**Comment by swiftyfinch** [comment]
Hello @anil291987!

Please, add more information about the issue.

1. Check that Pods project builds successfully without 🏈 Rugby.
2. Could you attach logs?
3. Could you attach your Podfile or the whole project?

Sorry, I can't help without additional information.

**Comment by swiftyfinch** [comment]
Also, if you are ready to fix the issue by yourself, feel free to open a pull request.
Perhaps, you can't share private information.

**Comment by anil291987** [comment]
Thanks, It is resolved. I am closing this issues.
