### ISSUE TITLE
🐛 TestProject + Rugby Beta does not work

### ISSUE THREAD

**Issue by marcosmko** [swiftyfinch/Rugby#217]
## Did you already try Rugby doctor?
does not work with beta

## Describe the bug

Using rugby with test project does not work

## To Reproduce
1. exclude `config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"` from Podfile
2. run `pod install && rugby cache -a arm64`
3. try running project
4. see that project does not compile with error `No such module 'SnapKit'`

## Expected behavior
To compile and run without errors

## Screenshots
seems like the command itself runs
```
Pod installation complete! There are 8 dependencies from the Podfile and 9 total pods installed.
⚑ Cache -a arm64
  ⚑ Build
    ✓ Getting Xcode CLT
    ✓ CLT: Xcode 14.2 (Build version 14C18)
    ✓ Reading Project
    ✓ Finding Build Targets
    ✓ Backuping
    ⚑ Checking Binaries Storage
      ✓ Calculating Storage Info
      ✓ Used: 0.01 GB (0%)
    ✓ Checking Binaries Storage
    ✓ [0.1s] Hashing Targets
    ✓ Finding Binaries
    ✓ Creating Build Target
    ✓ Saving Project
    ✓ [6.4s] Debug: sim-arm64 (9)
    ✓ Saving binaries (9)
  ✓ [6.7s] Build
  ⚑ Use
    ✓ Reading Project
    ✓ Finding Build Targets
    ✓ Hashing Targets
    ✓ Backuping
    ✓ Patching Product Files
    ✓ Deleting Targets (9)
    ✓ Saving Project
  ✓ [0.1s] Use
✓ [6.8s] Cache -a arm64
⚑ Let's Roll-oll 🏈
```

but after trying to un project I get this:

<img width="500" alt="Screenshot 2023-02-28 at 18 55 59" src="https://user-images.githubusercontent.com/9013995/221990396-360ebefc-1f1a-4223-8874-6aa185f65043.png">

## Environment (please complete the following information):
 - Version 2.0.0b5
 - Logs (use `rugby doctor`) N/A
 - Same from TestProject

## Additional context
Tried cleaning all caches but still getting error

**Comment by swiftyfinch** [comment]
Hello! Thank you for reporting.

I think the problem is here: https://github.com/swiftyfinch/Rugby/blob/main/TestProject/TestProject/TestProject.xcodeproj/project.pbxproj#L705

Could you try to remove this from Xcode project and try again?
I'm going to clean up this project from any excludes.

**Comment by marcosmko** [comment]
can confirm this worked, thanks!
