### ISSUE TITLE
👨🏻‍🔧 Increase Code Coverage

### ISSUE THREAD

**Issue by swiftyfinch** [swiftyfinch/Rugby#236]
Right now Rugby has the dramatically low code coverage `3%`.
I think that the minimal goal should be `50%`.
This badge is showing the current coverage percent.
<a href="https://app.codecov.io/gh/swiftyfinch/Rugby"><img src="https://img.shields.io/codecov/c/github/swiftyfinch/rugby/main?label=Coverage"></a>

It will be great ♥︎ if you can help and write some new tests here.
Feel free to book some of them in this issue and then open a pull request.

It should be counted in upcoming [Hacktoberfest](https://hacktoberfest.com).

## 🎯 Roadmap
- [x] RugbyFoundation/Core
  - [x] TargetsHasher
  - [x] BackupManager
  - [x] DeleteTargetsManager
  - [x] WarmupManager
  - [x] UseBinariesManager
  - [x] TargetTreePainter
  - [x] Cleaner
  - [x] BuildManager

**Comment by ameen4455** [comment]
Hi, I would like to help you with this

**Comment by swiftyfinch** [comment]
> Hi, I would like to help you with this

Hello @ameen4455! Feel free to select some tests 👍
