### ISSUE TITLE
🐛 Modulemap not found (2.0.3, Xcode 15)

### ISSUE THREAD

**Issue by rock88** [swiftyfinch/Rugby#242]
## Describe the bug
Hello! I faced with this Xcode error:

```
/Users/user/Tests/RugbyTest/Pods/Target Support Files/Pods-RugbyTest/Pods-RugbyTest-dummy.m module map file '/Users/user/Library/Developer/Xcode/DerivedData/RugbyTest-engmykdkznjnrcbmcwflmqvdswxq/Build/Products/Debug-iphonesimulator/Alamofire/Alamofire.modulemap' not found
```

## To Reproduce
1. Create a new Xcode iOS project from scratch;
2. Create a new Podfile with following content:
```ruby
source 'https://cdn.cocoapods.org'

platform :ios, '15.0'

use_modular_headers!
inhibit_all_warnings!

target 'RugbyTest' do
  pod 'Alamofire'
end
```
3. Run `pod install` and `rugby`;
4. Try to build the project.

## Expected behavior
Project should build without errors.

## Environment:
```
$ rugby
⚑ Cache
  ⚑ Build
    ✓ CLT: Xcode 15.0
    ✓ Reading Project
    ✓ Finding Build Targets
    ✓ Backuping
    ⚑ Checking Binaries Storage
      ✓ Calculating Storage Info
      ✓ Used: 0,47 GB (0%)
    ✓ Checking Binaries Storage
    ✓ Hashing Targets
    ✓ Finding Binaries
    ✓ Creating Build Target
    ✓ Saving Project
    ✓ [3.7s] Debug: sim-arm64 (1)
    ✓ Saving binaries (1)
  ✓ [3.8s] Build
  ⚑ Use
    ✓ Reading Project
    ✓ Finding Build Targets
    ✓ Hashing Targets
    ✓ Backuping
    ✓ Patching Product Files
    ✓ Deleting Targets (1)
    ✓ Saving Project
  ✓ Use
✓ [3.8s] Cache
✓ ⚑ Let's Roll-oll 🏈

$ rugby env
Rugby version: 2.0.3
Swift: 5.9
CLT: Xcode 15.0 (Build version 15A240d)
CPU: Apple M1 Pro (arm64)
Project: RugbyTest
Git branch: Unknown

$ pod --version
1.13.0
```

## Additional context
I found `Alamofire.modulemap` in `Pods/Target Support Files/Alamofire/Alamofire.modulemap` and if modify `Pods-RugbyTest.debug.xcconfig` from:

```
OTHER_CFLAGS = $(inherited) -fmodule-map-file=$(inherited) -D COCOAPODS -Xcc -fmodule-map-file="${PODS_CONFIGURATION_BUILD_DIR}/Alamofire/Alamofire.modulemap"
OTHER_SWIFT_FLAGS = $(inherited) -D COCOAPODS -Xcc -fmodule-map-file="${PODS_CONFIGURATION_BUILD_DIR}/Alamofire/Alamofire.modulemap"

to

OTHER_CFLAGS = $(inherited) -fmodule-map-file="${PODS_ROOT}/Target Support Files/Alamofire/Alamofire.modulemap"
OTHER_SWIFT_FLAGS = $(inherited) -D COCOAPODS -Xcc -fmodule-map-file="${PODS_ROOT}/Target Support Files/Alamofire/Alamofire.modulemap"
```

The project builds without errors, but if I try to use some object from Alamofire I got error:

```swift
import UIKit
import Alamofire

class ViewController: UIViewController {
    func test() {
        _ = AF // Error: Cannot find 'AF' in scope
    }
}
```

If I click with pressed Command key to `import Alamofire` I see next:

```swift
import UIKit

public var AlamofireVersionNumber: Double
public let AlamofireVersionString: <<error type>>
```

**Comment by swiftyfinch** [comment]
Hello @rock88! It's the same as #231.

Right now 🏈 Rugby doesn't support libraries.
So, you should add `use_frameworks!` to your Podfile.
Or, we need to add support of libraries in #231.

Please, let me know if you have another one issue.

**Comment by rock88** [comment]
@swiftyfinch oh, thank you for explain!

I made few manual fixes and seems like all works fine, I'll just write what I did step by step, maybe I can make a PR with fixes:

1. Only `libAlamofire.a` is not enough for static libraries, needs full set of modulemap/headers/etc:
Xcode produced this files:
<img width="654" alt="Screenshot 2023-10-05 at 21 50 25" src="https://github.com/swiftyfinch/Rugby/assets/323908/3eee07bc-4b7e-4a3b-a85c-a17aa0b95ded">



`Rugby` produced only `libAlamofire.a`:
<img width="497" alt="Screenshot 2023-10-05 at 21 52 04" src="https://github.com/swiftyfinch/Rugby/assets/323908/9beac0c9-40ea-4123-86e3-b1b3e1914417">



So I copied all files (except `libAlamofire.a`) to `${HOME}/.rugby/bin/Alamofire/.../5a9ab27`:
<img width="506" alt="Screenshot 2023-10-05 at 21 52 09" src="https://github.com/swiftyfinch/Rugby/assets/323908/b5edcdb1-c7c0-43fc-aa6c-e22e34198169">

2. Fix `Alamofire.modulemap` in `rugby` binary folder (`"${HOME}/.rugby/bin/Alamofire/.../5a9ab27"`):
Origin:
```swift
module Alamofire {
  umbrella header "Alamofire-umbrella.h"

  export *
  module * { export * }
}


module Alamofire.Swift {
  header "/Users/user/Library/Developer/Xcode/DerivedData/RugbyTest-engmykdkznjnrcbmcwflmqvdswxq/Build/Products/Debug-iphonesimulator/Alamofire/Swift Compatibility Header/Alamofire-Swift.h"
  requires objc
}
```

Fixed:
```swift
module Alamofire {
  umbrella header "Alamofire-umbrella.h"

  export *
  module * { export * }
}


module Alamofire.Swift {
  header "Swift Compatibility Header/Alamofire-Swift.h"
  requires objc
}
```

3. Fix paths in `Pods-RugbyTest.debug.xcconfig` (diff only):
Origin:
```
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/Alamofire" "${TOOLCHAIN_DIR}/usr/lib/swift/${PLATFORM_NAME}" /usr/lib/swift
OTHER_CFLAGS = $(inherited) -fmodule-map-file="${PODS_CONFIGURATION_BUILD_DIR}/Alamofire/Alamofire.modulemap"
OTHER_SWIFT_FLAGS = $(inherited) -D COCOAPODS -Xcc -fmodule-map-file="${PODS_CONFIGURATION_BUILD_DIR}/Alamofire/Alamofire.modulemap"
SWIFT_INCLUDE_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/Alamofire"
```

After `rugby` and manual fixes:
```
LIBRARY_SEARCH_PATHS = $(inherited) "${HOME}/.rugby/bin/Alamofire/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}-${ARCHS}/5a9ab27" "${TOOLCHAIN_DIR}/usr/lib/swift/${PLATFORM_NAME}" /usr/lib/swift
OTHER_CFLAGS = $(inherited) -fmodule-map-file="${HOME}/.rugby/bin/Alamofire/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}-${ARCHS}/5a9ab27/Alamofire.modulemap"
OTHER_SWIFT_FLAGS = $(inherited) -D COCOAPODS -Xcc -fmodule-map-file="${HOME}/.rugby/bin/Alamofire/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}-${ARCHS}/5a9ab27/Alamofire.modulemap"
SWIFT_INCLUDE_PATHS = $(inherited) "${HOME}/.rugby/bin/Alamofire/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}-${ARCHS}/5a9ab27"
```

**Comment by swiftyfinch** [comment]
Great news! You are right, I made the similar steps yesterday. And I have almost made a draft. But after that I found an issue with [`Keyboard+LayoutGuide`](https://github.com/swiftyfinch/Rugby/blob/main/Example/Podfile#L8C8-L8C28) `modulemap` naming. And it needs some polishing.

I think there are such ways:
1) You can open your own pull request if you like to continue solving the issue. You are welcome here!
2) I can continue working on my draft this evening and maybe I will try to open pull request.

I can't share it right now, because I'm on the different mac.

**Comment by swiftyfinch** [comment]
@rock88 This feature will be available in the next release 🚢
Thank you for your help!

**Comment by rock88** [comment]
@swiftyfinch 🏈🚀 Many thanks!
