### ISSUE TITLE
Support multiple architectures?

### ISSUE THREAD

**Issue by PRESIDENT810** [swiftyfinch/Rugby#249]
## Describe the bug
I was trying to build a target for iPhone simulator device on a M2 chip MacBook. However I got this error:

<img width="1107" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/9f9cef6e-c4b6-4849-954d-3029b84922bc">

I'm a iOS development noob so I'm not 100% sure what happened. I guess for some reason Xcode is trying to build both x86_64 and arm64 architecture, but rugby seems can only generate one architecture?

I tried to use rugby cache --arch, but it only supports "auto, x86_64 or arm64", and generated pod cache only has "\~/.rugby/bin/Alamofire/Internal-iphonesimulator-arm64" or "\~/.rugby/bin/Alamofire/Internal-iphonesimulator-x86_64" but not "\~/.rugby/bin/Alamofire/Internal-iphonesimulator-arm64 x86_64".

Not sure if it's because I'm using it wrong, or we need to make rugby generate both arm64 and x86_64 arch.

I'm using rugby with commit SHA=4054bcca22739e086d6f8fde3ce12b7f2f807a4f, and I'm using static libraries.

**Comment by swiftyfinch** [comment]
@PRESIDENT810 Hello!

Do you select `Any iOS Simulator Device (arm64, x86_64)`?

<img width="700" src="https://github.com/swiftyfinch/Rugby/assets/64660122/a1b405a2-a5ee-4329-a478-de1a5ac141c7">

<br>
<br>

If it so, you should use the concrete destination instead. For example, `iPhone 15`.

<img width="700" src="https://github.com/swiftyfinch/Rugby/assets/64660122/4e5395d8-be60-4c79-b906-92ab17540022">

**Comment by PRESIDENT810** [comment]
Yes I'm using Any iOS Simulator Device (arm64, x86_64). Does rugby only support when building for one single arch?

I tried to use arm64 /x86_64 separately and it's working

**Comment by swiftyfinch** [comment]
@PRESIDENT810 Yeah, 🏈 Rugby uses `${ARCHS}` variable.
And when you build for several destinations at once, this variable contains all of them.

It's a kind of limitation. I don't have a better idea of how to construct dynamic paths.

But, you can build both architectures with Rugby and then build any single destination in Xcode.
https://github.com/swiftyfinch/Rugby/blob/main/Docs/commands-help/build.md#discussion

**Comment by PRESIDENT810** [comment]
Cool, I think that also works for me. Feel free to close this issue, thanks!
