### ISSUE TITLE
🐛 There are two styles of LD_RUNPATH_SEARCH_PATHS in hash context

### ISSUE THREAD

**Issue by cragod** [swiftyfinch/Rugby#308]
## Have you already tried Rugby doctor?
Yes

## Describe the bug
We found that `LD_RUNPATH_SEARCH_PATHS` on different machines is inconsistent in the hash context, resulting in the cache being unable to be reused.

## To Reproduce
1. Checkout the same node from the project repo
2. Try using the published cache
3. Unable to use because hash is inconsistent

## Expected behavior
The hash context should be consistent to hit cache

## Screenshots
![image](https://github.com/swiftyfinch/Rugby/assets/4200196/228e01c5-f5dc-4b21-a45d-475f3317def0)

## Environment (please complete the following information):
 - Version 2.4.4

**Comment by swiftyfinch** [comment]
@cragod Hello!

Could you check your project content `Example/Pods/Pods.xcodeproj/project.pbxproj`?

<img width="943" alt="Screenshot 2023-12-08 at 18 04 08" src="https://github.com/swiftyfinch/Rugby/assets/64660122/34f2618a-743f-451f-a78a-18e3427c4e28">

- Do you have an array or a string there? Can you have a different project generation process on your CI?
- Also, I've checked Xcodeproj and I see that it should be an array. Could it be that you concat `LD_RUNPATH_SEARCH_PATHS` by a mistake?
  https://github.com/tuist/XcodeProj/blob/338e9838d28306ce705c6afde4cd84939f4da125/Tests/XcodeProjTests/Utils/BuildSettingsProviderTests.swift#L18

**Comment by cragod** [comment]
Yes, there are two different setting styles in Pods.xcodeproj. However, it's strange that their `bundle` processing flows are consistent, and I couldn't find any logic that modifies this item. I think I need to investigate further to find the reason🤔

**Comment by cragod** [comment]
I still haven't found the root cause of this issue. For now, we can only patch the target hasher to work around it in our current environment. Perhaps we can close it for now and discuss it again when we have more clues? @swiftyfinch

**Comment by swiftyfinch** [comment]
@cragod Yeah, feel free to close it.

I can suggest to check:
- That you use the same version (including patch) of CocoaPods on your local and remote environments;
- The same with Xcode version (including patch);
- And you do not modify Pods project in a different way in some `post_install` hooks;
- Or may be you have some additional steps after project generation by CocoaPods?

Also, I think that we can convert all arrays in build settings to strings.
May be it will be a reasonable patch and we will have a stable build settings format `[String: String]` instead of `[String: Any]`.

**Comment by cragod** [comment]
> * That you use the same version (including patch) of CocoaPods on your local and remote environments;
> * The same with Xcode version (including patch);
> * And you do not modify Pods project in a different way in some `post_install` hooks;
> * Or may be you have some additional steps after project generation by CocoaPods?

Thanks for your suggestions. We have checked all of these, but we have not found the cause. Moreover, there may be differences when pulling the same branch to two different directories on the same device. It's a bit magical.

> Also, I think that we can convert all arrays in build settings to strings.
> May be it will be a reasonable patch and we will have a stable build settings format `[String: String]` instead of `[String: Any]`.

This is a good solution. What we are doing now is similar to this. We remove the quotes from items then join them into a string. However, for the official version, it may require more testing. Looking forward to further updates and improvements :)
