### ISSUE TITLE
🔭 Authentication headers support for remote cache

### ISSUE THREAD

**Issue by dcacenabes** [swiftyfinch/Rugby#329]
## Problem statement
Some remote cache providers require authentication via http headers.
e.g. Artifactory expects a "X-JFrog-Art-Api" header containing an API key.

## Describe the solution you'd like
When fetching cache, have the possibility to define headers for authentication, ideally via parameters to the command call. e.g.
rugby warmup --headers "X-JFrog-Art-Api:my-api-key"?

## Describe alternatives you've considered
Reading headers from environment variables

## Additional context
I have validated that this works by adding:
`urlRequest.addValue("my-api-key", forHTTPHeaderField: "X-JFrog-Art-Api")`
to the CacheDownloader's `download(_ url: URL)` and ReachabilityChecker's `checkIfURLIsReachable(_ url: URL)` functions.

If you think this is an interesting feature, I would even be willing to implement it. I would like to get to an agreement on the best way to provide those headers.

**Comment by swiftyfinch** [comment]
Hello @dcacenabes! Yeah, feel free to open a draft pull request 👍
