### ISSUE TITLE
relative paths

### ISSUE THREAD

**Issue by AF-pfo** [swiftyfinch/Rugby#331]
Is there still the possibility to use relative paths like in this [issue](https://github.com/swiftyfinch/Rugby/issues/153)?

**Comment by swiftyfinch** [comment]
Hello @AF-pfo! Why do you need this option?
Right now, by default 🏈 Rugby v2x keeps all binaries in one folder `~/.rugby/bin`.
So I think, there shouldn't be any issue with relative paths.

**Comment by swiftyfinch** [comment]
@AF-pfo Could you attach a log with an error from `.rugby/logs` folder?
Or do you have errors in Xcode logs?

**Comment by swiftyfinch** [comment]
I'm going to close this issue due to inactivity.
If you have any additional information, please feel free to reopen this issue.
