### ISSUE TITLE
🔭 Add support arm64 for the simulator

### ISSUE THREAD

**Issue by swiftyfinch** [swiftyfinch/Rugby#57]
Try to add support arm64 for the simulator on m1. But probably, it should be beyond 🏈 **Rugby** https://github.com/bogo/arm64-to-sim

**Comment by swiftyfinch** [comment]
Closed, because it's better to take out beyond 🏈 Rugby

**Comment by gf0x** [comment]
Hello!
Could you please provide some tips on how to make Rugby work on M1 hosts? As for now no errors/warnings appear, only successful output in terminal. However, nothing no changes in `.rugby/build` folder take place.

**Comment by swiftyfinch** [comment]
@gf0x Hey! Do you see a folder that contains `x86_64` in `.rugby/build`?
If you want to build for m1 native architecture you need to use the `arch` option.

For example:
```shell
rugby cache --arch arm64 --sdk sim
```

If it won't help you please open a new discussion/issue.
