### ISSUE TITLE
🔭 Build both ios and sim SDKs

### ISSUE THREAD

**Issue by swiftyfinch** [swiftyfinch/Rugby#58]
Build both ios and sim **SDKs** and merge them into **XCFramework**. Several people requested this feature.
For example, #1 #35 #41

**Comment by muukii** [comment]
I hope this feature.

**Comment by muukii** [comment]
Actually, I did try to create this. but I could not do that.
- I don't know details of handling resources.
- a bit hard to re-writing xcconfig file, also reverting function. I attempted to stop using complex regex.

I'd like to get what we got tasks to achieve this feature.

**Comment by swiftyfinch** [comment]
Hey, @muukii thank you for supporting me! I appreciate it a lot 👍🏻
It's not easy to make this feature. I need some time to dive into it.

I'm not sure that I understand your last comment. Do you have a draft?
Could you describe how you are going to use this feature? It can be useful for implementation.

- 💡 The first idea I have it's to reuse the current implementation of building for a separate platform.
Then I think we just need a smarter way to patch `xcconfig` files;
- I'm not sure about removing complex `regex`, because it's all about optimizations. But I know about this inconvenient part and will try to do my best;
- Also, Rugby 🏈 doesn't have the function of reverting `xcconfig` files. It's pity and probably should be fixed in a different issue.

**Comment by muukii** [comment]
thank you for replying
my wip branch is here: https://github.com/muukii/Rugby/tree/muukii/multiple-arch

**Comment by swiftyfinch** [comment]
@muukii Hello! You can check this feature from master:
```shell
mint install rugby@main
pod install
rugby cache --sdk sim ios
```
