### ISSUE TITLE
Error: Couldn't find pods targets.

### ISSUE THREAD

**Issue by faimin** [swiftyfinch/Rugby#81]
```shell
> rugby 
Prepare Calculate checksums ⏱
⛔️ Error: Couldn't find pods targets.
🚑 Try to call pod install.
🚑 Call doctor for more help: rugby doctor
```

rugby version: `1.13.0`
Xcode: `13.1`
Mac OS: `11.6.1`

test demo： [https://github.com/faimin/ZDFlexLayoutKit](https://github.com/faimin/ZDFlexLayoutKit)  ,  branch: `dev`

**Comment by cielpy** [comment]
run `pod install` before run `rugby`
