### ISSUE TITLE
duplicate symbol '_NDR_record' in ld: 1 duplicate symbol for architecture x86_64

### ISSUE THREAD

**Issue by Wei-Pinkoi** [swiftyfinch/Rugby#83]
cat .rugby/build.log

```
[pop] Touching pop.framework
[nanopb] Touching nanopb.framework
❌ duplicate symbol '_NDR_record' in
❌ ld: 1 duplicate symbol for architecture x86_64
❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

from Podfile.lock
- Koloda (5.0.1):
    - pop (~> 1.0)
- FirebaseCrashlytics (7.3.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleDataTransport (~> 8.0)
    - nanopb (~> 2.30906.0)
    - PromisesObjC (~> 1.2)

**Comment by Wei-Pinkoi** [comment]
log updated.
[build.log](https://github.com/swiftyfinch/Rugby/files/7564316/build.log)
[rawBuild.log](https://github.com/swiftyfinch/Rugby/files/7564317/rawBuild.log)
[rugby.log](https://github.com/swiftyfinch/Rugby/files/7564319/rugby.log)

**Comment by Wei-Pinkoi** [comment]
Okay, seem that pod Nimble cause the issue. 
I disabled Nimble and result is pretty.

**Comment by Wei-Pinkoi** [comment]
ld: warning: directory not found for option '-F/Users/pinkoi/Library/Developer/Xcode/DerivedData/Test-dkrptqvvvznkzobutyvbqcpbdwok/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/FirebasePerformance'
ld: warning: directory not found for option '-F/Users/pinkoi/Library/Developer/Xcode/DerivedData/Test-dkrptqvvvznkzobutyvbqcpbdwok/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Reveal-SDK'
ld: warning: directory not found for option '-F/Users/pinkoi/Library/Developer/Xcode/DerivedData/Test-dkrptqvvvznkzobutyvbqcpbdwok/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Survicate'

**Comment by swiftyfinch** [comment]
Hello @Wei-Pinkoi! I'm not sure, is it still the issue for you?

**Comment by Wei-Pinkoi** [comment]
Sorry for lately reply, could I close the issue and raise new issue when found. Thnkas

**Comment by swiftyfinch** [comment]
@Wei-Pinkoi Yeah, no problem. Feel free to do it 👍

**Comment by swiftyfinch** [comment]
## Please, feel free to open new issue with these templates:

<img width="407" alt="Screenshot 2021-11-21 at 21 01 19" src="https://user-images.githubusercontent.com/64660122/142773605-3715f9cb-e4d8-4c8b-8ed2-fc2ce9668263.png">

**Comment by Wei-Pinkoi** [comment]
@swiftyfinch 
Just the record, for people who suffering this issue.
```
❌ duplicate symbol '_NDR_record' in
❌ ld: 1 duplicate symbol for architecture x86_64
```
At plan.yml, exclude add those pods.
```
- command: cache
  exclude: [Quick, Nimble, Nimble-Snapshots]
```

ref: https://githubmemory.com/repo/Quick/Nimble/issues/913

**Comment by swiftyfinch** [comment]
Thanks a lot @Wei-Pinkoi 👍
Feel free to ask any questions about `plans.yml` in discussions.
