### ISSUE TITLE
Cocoapods subspecs

### ISSUE THREAD

**Issue by denandreychuk** [swiftyfinch/Rugby#85]
Installing additional subspecs from the same module break logic. New added subspec not visible inside project.

**Comment by swiftyfinch** [comment]
@denandreychuk Hello! Could you describe step by step what you do?
I tried adding a new subspec to TestProject and it worked fine.

**Comment by swiftyfinch** [comment]
## Please, feel free to open new issue with these templates:

<img width="407" alt="Screenshot 2021-11-21 at 21 01 19" src="https://user-images.githubusercontent.com/64660122/142773605-3715f9cb-e4d8-4c8b-8ed2-fc2ce9668263.png">
