### ISSUE TITLE
Error on building project after integrating Rugby

### ISSUE THREAD

**Issue by prgorasiya** [swiftyfinch/Rugby#87]
**Did you already try Rugby doctor?**
Yes

**Describe the bug**
I have 2 different projects(lets call them Project A & B) and they share some pods. I integrated rugby to first project A successfully without any issue.
However, after integrating rugby with my 2nd project B I am getting this error when I try to build project B:
```
ld: library not found for -lAppAuth
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I dont know what framework is this, doesnt look like any from my pod file.

**To Reproduce**
Not sure because rugby is working fine with one of my other project.

**Expected behavior**
rugby should integrate without any error to my 2nd project as well.

**Environment (please complete the following information):**
 - Version 1.13.0
 - Logs (use `rugby doctor`)
 - Podfile or Example project (if you can share these)
[rawBuild-log.txt](https://github.com/swiftyfinch/Rugby/files/7579042/rawBuild-log.txt)
[rugby-log.txt](https://github.com/swiftyfinch/Rugby/files/7579043/rugby-log.txt)
[cache-yml.txt](https://github.com/swiftyfinch/Rugby/files/7579048/cache-yml.txt)

**Comment by swiftyfinch** [comment]
Hello @prgorasiya, I will look through that soon.

I wonder if you can share your project's Podfile?
Could you describe your project's folder structure? How do you share pods between them?

**Comment by prgorasiya** [comment]
Hi @swiftyfinch 
You can find pods used in cache-yml file.
What do you mean by project's folder structure?

Both projects are separate and when I say they share some pods means they use some pods with in their projects, not like a shared framework/target. Both projects are independent.
Example: both projects use some firebase SDKs

So I guess after integrating rugby they would share the cache, but not sure how that works for rugby.

**Comment by swiftyfinch** [comment]
@prgorasiya Thank you for the details.
And sorry, I need more time to check this issue.

**Comment by prgorasiya** [comment]
sure, no prob.
thanks

**Comment by swiftyfinch** [comment]
@prgorasiya What configuration do you build? Maybe it's not `Debug`? So, you should switch it to `Debug` in your Xcode project or use the command `rugby cache --config YOUR_CONFIGURATION`.

And are you sure that you open `.xcworkspace`? Also, such a problem can be if you open just `.xcodeproj`.

**Comment by swiftyfinch** [comment]
I couldn't find issues in your pods configuration. That all seems OK.
Also, did you try to build that project without 🏈 Rugby? Is everything good?

**Comment by Wei-Pinkoi** [comment]
@prgorasiya 
I have so complexity podfile, but I work fine on 1.14.0/1.13.0
[PodfileExample.txt](https://github.com/swiftyfinch/Rugby/files/7592405/PodfileExample.txt)

But actually some pod will fail, you can exclude those pod
ref: https://github.com/swiftyfinch/Rugby/issues/83

Hope all well

**Comment by prgorasiya** [comment]
@swiftyfinch yes i am building for `debug` only, and also opening `.xcworkspace`. Yet its giving me error on building.
I can build the project successfully without rugby.

**Comment by prgorasiya** [comment]
@Wei-Pinkoi I'll try your approach.

**Comment by prgorasiya** [comment]
@swiftyfinch just to add on, I deleted `.rugby` folder from my project B, cleaned the project, deleted derived data folder, then tried to build the project, it was successful.
Then I integrated rugby using `pod install && rugby`, tried to build the project but got the same error as I have highlighted.

**Comment by swiftyfinch** [comment]
@prgorasiya Sorry, I don't have new ideas.

Can I ask you to prepare an example application? You can base it on `TestProject` from this repo if you wish.
Feel free to fork this repository and break `TestProject` with your configuration. And I will try to fix it.

**Comment by prgorasiya** [comment]
@swiftyfinch I upgarded to V1.14.0 and I can successfully build both projects after selecting any iphone simulator.
However, if i select a physical device or Any iOS Device(arm 64) option from run options I am getting the same error.
I even completely re-integrated rugby with both my projects but no luck. Could this also happen with `TestProject`? I havent tried that.

Besides that, may I know whats the use of this from pod file of `TestProject`

```
installer.pods_project.targets.each do |target|
    if target.name.include? 'LocalPod'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
      end
    end
  end
  
  installer.pods_project.root_object.build_configuration_list.build_configurations.each { |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  }
```

**Comment by prgorasiya** [comment]
@swiftyfinch I managed to replicate the issue with a sample project.
Please find attahced zip file, run `pod install && rugby` then open the project and select Any iOS Device(arm64) as a run destination and you'll see the error. The error can also be replicated by selecting a physical device.

Sample Project:
[AA.zip](https://github.com/swiftyfinch/Rugby/files/7607360/AA.zip)

**Comment by swiftyfinch** [comment]
First of all, thank you for your investigation!

> @swiftyfinch I upgarded to V1.14.0 and I can successfully build both projects after selecting any iphone simulator.

That's something 👍

> run pod install && rugby then open the project and select Any iOS Device(arm64) as a run destination and you'll see the error. The error can also be replicated by selecting a physical device.

You need to use such command `pod install && rugby -s sim ios`. Check out [docs](https://github.com/swiftyfinch/Rugby/blob/main/Docs/Cache.md#build-both-sdks-sim-x86_64-ios-arm64) for more information.

This block converts all warnings to errors:
```ruby
installer.pods_project.targets.each do |target|
  if target.name.include? 'LocalPod'
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
    end
  end
end
```

This block for building x86_64 on m1 MacBook:
```ruby
installer.pods_project.root_object.build_configuration_list.build_configurations.each { |config|
  config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
}
```

**Comment by prgorasiya** [comment]
@swiftyfinch thanks for the detailed info.
Should I use `pod install && rugby --config Debug` if I want to run my project on simulator and a physical device?
Mainly I sometime test my app on device and other times on simulator, so which command should I use so that I can build pods in one-shot?

**Comment by swiftyfinch** [comment]
@prgorasiya 
If you want to build for simulator only it's better to use `pod install && rugby`.
It equals to `pod install && rugby cache --sdk sim --config Debug`
That's will be enough and the build will take less time.

But if you want to build for simulator and device you need to use `pod install && rugby -s sim ios`.

**Comment by prgorasiya** [comment]
@swiftyfinch I am still unable to build Project B, even after using the command `pod install && rugby -s sim ios`.
I am getting the same error.
I deleted `.rugby` folder from my project folder and tried to integrate it again. Upon comparing `.rugby` folder of Project B with Project A, I can see that there's no `build` forlder generated for project B. I tried multiple times but its the same.
Could that be a problem? and what could be the reason for build folder to not get generated?

**Comment by swiftyfinch** [comment]
@prgorasiya Hey! Are you sure that you deleted the whole `.rugby` folder? May only `.rugby/build`?
If you didn't delete `.rugby/cache.yml` file it is can be an issue.
Please, use `rugby clean` for that if you didn't.

Could you send me your `.rugby/rugby.log` file? Or you can check it out by yourself. Do you see there `[Build] Skip` line?

**Comment by prgorasiya** [comment]
@swiftyfinch yes i did delete entire `.rugby` folder. I even tried `rugby clean` and tried to reintegrate rugby, but in all cases build folder is not getting generate for this project and I am still getting the same error.

Here is the log file.
[rugby-log.txt](https://github.com/swiftyfinch/Rugby/files/7622273/rugby-log.txt)

**Comment by swiftyfinch** [comment]
@prgorasiya Please, try this command to find the build directory path
```sh
grep "SYMROOT" --color .rugby/rawBuild.log
```
What do you see there?

**Comment by swiftyfinch** [comment]
And will be great if you can provide an example project for reproducing the issue.
I didn't see anything similar before.

**Comment by prgorasiya** [comment]
Hi @swiftyfinch this the out put of the command, I ran the command within project B's folder, I hope I did the right thing.
My project B's folder name is 2 words with a space in between, just to add on.
```
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project Pods/Pods.xcodeproj -scheme RugbyPods -sdk iphoneos SYMROOT=/Users/paras/<Project B name>/.rugby/build COMPILER_INDEX_STORE_ENABLE=NO SWIFT_COMPILATION_MODE=wholemodule ARCHS=arm64 -config Debug
    SYMROOT = /Users/paras/<First word of Project B's folder name>
```
Its wierd that at the end of the output it prints partial name of project B's folder.

Also, this is zip file containing 2 projects which uses same pods. Try to play around with building for simulator, any ios device and a physical device.
[Archive.zip](https://github.com/swiftyfinch/Rugby/files/7626126/Archive.zip)

**Comment by swiftyfinch** [comment]
@prgorasiya Thank you for more info! You can check out pull request #99 
Please, try to install `mint install rugby@bugfix/missing_build_folder`

**Comment by prgorasiya** [comment]
Hi @swiftyfinch thanks for the quick fix. Its working fine now. Just a question, if i clean my project and also delete everything from derived data folder, do I need to run `pod install && rugby -s sim ios` again?

**Comment by swiftyfinch** [comment]
@prgorasiya No, you don't need it.
That is because 🏈 Rugby keeps all frameworks in the `.rugby/build` folder.

**Comment by prgorasiya** [comment]
@swiftyfinch I just got one more question. When I try to archive I am getting the same error.
`ld: library not found for -lAppAuth`

So do I need to build rugby for any other configuration? So that I can run on simulator, device and also archive to release a dev build for testers?

**Comment by swiftyfinch** [comment]
@prgorasiya Yeah, but there are some problems with that.

Discussion:
https://github.com/swiftyfinch/Rugby/discussions/88#discussioncomment-1687810

Requests:
#93

Check out documentation:
[Build both sdks (sim x86_64, ios arm64)](https://github.com/swiftyfinch/Rugby/blob/main/Docs/Cache.md#build-both-sdks-sim-x86_64-ios-arm64)
[Build for specific configuration](https://github.com/swiftyfinch/Rugby/blob/main/Docs/Cache.md#build-for-specific-configuration)
[Build for AppStore (for example)](https://github.com/swiftyfinch/Rugby/blob/main/Docs/Cache.md#build-for-appstore-for-example)

**Comment by prgorasiya** [comment]
@swiftyfinch so is it under development? Or is there a workaround I can use, in the mean time, to build for archive? So that I can successfully archive dev build. Currenlty, in order to deploy a dev version, I had to remove rugby from my project because of the error.

**Comment by swiftyfinch** [comment]
@prgorasiya You can try to install the dev version: `mint install rugby@main -f`
And then use 🏈 Rugby for archive builds like this: `rugby cache --sdk ios --config Release --bitcode`

Yeah, the main problem, for now, is building different combinations of sdk, config, and arch.
You can build any configurations, but separately https://github.com/swiftyfinch/Rugby/discussions/88#discussioncomment-1687810.
It's under development and I'm not sure how fast it will be released.

**Comment by prgorasiya** [comment]
@swiftyfinch it works for me, but then I am getting error when I run on simulator.
Building rugby with different build config also doesnt work for me.

**Comment by swiftyfinch** [comment]
@prgorasiya I think as a workaround you can build all your combinations separately:
```shell
# For archive builds
pod install && rugby cache --sdk ios --config Release --bitcode

# And for debug on simulator and device
pod install && rugby cache --sdk ios sim --config Debug
```

**Comment by prgorasiya** [comment]
@swiftyfinch you mean i should run first command before archiving dev build for testers?

**Comment by swiftyfinch** [comment]
Yes, but '--bitcode' option has not released yet. You can try it 'mint install swiftlyfinch/rugby@main’
