### ISSUE TITLE
🔭 Support any combinations of sdk, arch, and config

### ISSUE THREAD

**Issue by swiftyfinch** [swiftyfinch/Rugby#93]
## Is your feature request related to a problem? Please describe.
At present time, 🏈 Rugby can't build different combinations of sdk, arch, and config.
But there are few requests for this feature.

## Describe the solution you'd like
`todo:` Need to think about:
- [ ] How to change command interface?
- [x] How to change the path to building folders (Debug-iphonesimulator-ARCH)?
- [x] How to build each combination?
- [x] How to save and reuse them in cache.yml

## Describe alternatives you've considered
Now, 🏈 Rugby can build combinations by separate calls. All cache folders should be kept.

## Additional context
Discussions: #88
Twitter: [Does that actually support multiple archs?](https://twitter.com/muukii_app/status/1462274338350981121?s=20)

**Comment by Wei-Pinkoi** [comment]
Memo:
`.rugby/build/Debug-maccatalyst/HTMLEntities`
iOSAppOnMac -> maccatalyst

**Comment by swiftyfinch** [comment]
@Wei-Pinkoi Hey! What do you mean?

**Comment by Wei-Pinkoi** [comment]
I build iOS app with Mac, and get this error message.

So I think it should support the following on future.
iOSDevices/iosSimulator/maccatalyst

**Comment by swiftyfinch** [comment]
OK, but I think it's not related to this feature

**Comment by Wei-Pinkoi** [comment]
Okay, I totally reply at wrong place.
But hope this feature coming.

**Comment by Shadester** [comment]
Would love to have this!

**Comment by swiftyfinch** [comment]
I'm going to release public beta version soon)

**Comment by swiftyfinch** [comment]
I've implemented this feature in [🏈 Remastered (Early Beta)](https://github.com/swiftyfinch/Rugby/releases/tag/2.0.0b2).

**Comment by brunoald** [comment]
Hello, folks! First, thanks @swiftyfinch for this tool. It's awesome!

So, the project I work on has a couple different configs. Let's call then `DebugA` and `DebugB`. 

How can I build for all of them at once? 

The `-c` attribute seems to accept just a single Config name.

**Comment by swiftyfinch** [comment]
@brunoald Hello! Thank you!

In the new beta version you can do it like so:
https://github.com/swiftyfinch/Rugby/blob/2.0.0b2/docs/Migration%20Guide.md#cache--build--use

Unfortunately, in the current stable version you can try only this:
https://github.com/swiftyfinch/Rugby/discussions/88#discussioncomment-1687810

**Comment by bluepi0j** [comment]
Hey @swiftyfinch, is there workaround to build both `sim x86` and `sim arm64` in the current stable version (image1), it will override(image2) existing one, I checked the beta one. but it seems beta doesn't support exclude Pods now, our project need to exclude some Pods, otherwise it will have some error
<img width="970" alt="image" src="https://user-images.githubusercontent.com/3591809/219427057-2f0bfcba-5d25-4a50-9c7f-0c71d00e54f3.png">
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/3591809/219427317-2bcf68c4-38a5-4d31-ae0d-f166d72d4363.png">

**Comment by swiftyfinch** [comment]
Hello @bluepi0j!

Unfortunately, there isn't any solution for Rugby 1.x.

But you can use beta 2.x like so:
```
rugby build --arch arm64 --sdk sim
rugby build --arch arm64 --sdk ios
rugby use
```
https://github.com/swiftyfinch/Rugby/blob/2.0.0b5/docs/Migration%20Guide.md#cache--build--use

If you need to exclude some pods, use `exclude` option:
```
rugby --exclude PodA --except-as-regex "CompanyPod.*"
```
https://github.com/swiftyfinch/Rugby/blob/2.0.0b5/docs/Documentation/Shortcuts/Cache.md

Also, you can do it in plan. Please, write me if you have some problems with creating a plan.

**Comment by bluepi0j** [comment]
@swiftyfinch do you mean `rugby --except PodA`, right? Also in `plans.yml`, we need use `except: [PodA, PodB]`; instead of `exclude: [PodA, PodB]`. When I use exclude, there is error

**Comment by bluepi0j** [comment]
Also when I use except, it seems it doesn't except it
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/3591809/219472782-377c82b0-9fa1-424e-957a-6d55c805fea6.png">
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/3591809/219472843-42fe141f-eabf-4c69-b826-633e1841aba9.png">

**Comment by swiftyfinch** [comment]
> @swiftyfinch do you mean `rugby --except PodA`, right? Also in `plans.yml`, we need use `except: [PodA, PodB]`; instead of `exclude: [PodA, PodB]`. When I use exclude, there is error

Yes, I changed api in the new major version.
You can check it like so: `rugby cache -h`

**Comment by swiftyfinch** [comment]
> Also when I use except, it seems it doesn't except it
> <img alt="image" width="1788" src="https://user-images.githubusercontent.com/3591809/219472782-377c82b0-9fa1-424e-957a-6d55c805fea6.png">
> <img alt="image" width="1376" src="https://user-images.githubusercontent.com/3591809/219472843-42fe141f-eabf-4c69-b826-633e1841aba9.png">

It looks like you have old version. You can check it: `rugby --version`.
Try to update to the latest beta: `rugby update --beta`.
